name: CI/CD Pipeline for Dockerized Static Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-dockerhub-username/my-static-website:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH into Azure VM and deploy Docker container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_VM_HOST }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
          script: |
            docker pull your-dockerhub-username/my-static-website:latest
            docker stop my-static-website || true
            docker rm my-static-website || true
            docker run -d -p 80:80 --name my-static-website your-dockerhub-username/my-static-website:latest

            